/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPhotosRouteImport } from './routes/_app/photos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppProposalsIndexRouteImport } from './routes/_app/proposals/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppProposalsProposalIdRouteImport } from './routes/_app/proposals/$proposalId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppContractsContractIdRouteImport } from './routes/_app/contracts/$contractId'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosRoute = AppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsIndexRoute = AppProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsProposalIdRoute = AppProposalsProposalIdRouteImport.update({
  id: '/proposals/$proposalId',
  path: '/proposals/$proposalId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsContractIdRoute = AppContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/photos': typeof AppPhotosRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/proposals/': typeof AppProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/photos': typeof AppPhotosRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/contracts': typeof AppContractsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/proposals': typeof AppProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/photos': typeof AppPhotosRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/contracts/$contractId': typeof AppContractsContractIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/proposals/': typeof AppProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/photos'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/invoices/$invoiceId'
    | '/projects/$projectId'
    | '/proposals/$proposalId'
    | '/clients/'
    | '/contracts/'
    | '/invoices/'
    | '/projects/'
    | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/photos'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/invoices/$invoiceId'
    | '/projects/$projectId'
    | '/proposals/$proposalId'
    | '/clients'
    | '/contracts'
    | '/invoices'
    | '/projects'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/photos'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/clients/$clientId'
    | '/_app/contracts/$contractId'
    | '/_app/invoices/$invoiceId'
    | '/_app/projects/$projectId'
    | '/_app/proposals/$proposalId'
    | '/_app/clients/'
    | '/_app/contracts/'
    | '/_app/invoices/'
    | '/_app/projects/'
    | '/_app/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos': {
      id: '/_app/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AppPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals/': {
      id: '/_app/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AppProposalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals/$proposalId': {
      id: '/_app/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AppProposalsProposalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId': {
      id: '/_app/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AppContractsContractIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPhotosRoute: typeof AppPhotosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppContractsContractIdRoute: typeof AppContractsContractIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProposalsProposalIdRoute: typeof AppProposalsProposalIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProposalsIndexRoute: typeof AppProposalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPhotosRoute: AppPhotosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppContractsContractIdRoute: AppContractsContractIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProposalsProposalIdRoute: AppProposalsProposalIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProposalsIndexRoute: AppProposalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
